name: CI/CD

on:
  push:
    branches: dev

jobs:
  setup:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

  installDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run the tests
        run: npm test
